def get_translation(key, lang):
    translations = {
        "fr": {
            "category": "Catégorie",
            "subcategory": "Sous-catégorie",
            "supplier": "Fournisseur",
            "product_name": "Nom du produit",
            "quantity": "Quantité",
            "price": "Prix unitaire",
            "date": "Date",
            "save": "Enregistrer",
            "purchase_history": "Historique des achats",
            "no_purchases": "Aucun achat trouvé.",
            "add_product": "Ajouter un produit",
            "total": "Total",
            "comparison_weekly": "🔁 Comparaison Hebdomadaire",
            "statistics": "📈 Statistiques",
            "monthly_expense": "💰 Dépenses Mensuelles",
            "daily_total": "Total journalier",
            "weekly_total": "Total hebdomadaire",
            "monthly_total": "Total mensuel",
            "quarterly_total": "Total trimestriel",
            "difference_7j": "Différence 7 jours",
            "difference_30j": "Différence 30 jours",
            "select_month": "Sélectionner un mois",
        },
        "ar": {
            "category": "الصنف",
            "subcategory": "الصنف الفرعي",
            "supplier": "المزوّد",
            "product_name": "اسم المنتج",
            "quantity": "الكمية",
            "price": "السعر الفردي",
            "date": "التاريخ",
            "save": "حفظ",
            "purchase_history": "سجل المشتريات",
            "no_purchases": "لا توجد مشتريات.",
            "add_product": "إضافة منتج",
            "total": "المجموع",
            "comparison_weekly": "🔁 المقارنة الأسبوعية",
            "statistics": "📈 الإحصائيات",
            "monthly_expense": "💰 نفقات الشهر",
            "daily_total": "المجموع اليومي",
            "weekly_total": "المجموع الأسبوعي",
            "monthly_total": "المجموع الشهري",
            "quarterly_total": "المجموع الفصلي",
            "difference_7j": "الفرق ٧ أيام",
            "difference_30j": "الفرق ٣٠ يوما",
            "select_month": "اختر الشهر",
        }
    }

    return translations.get(lang, {}).get(key, key)

