# lang_utils.py

def get_translation(key: str, lang: str) -> str:
    translations = {
        "fr": {
            "Add a product": "Ajouter un produit",
            "Category": "Catégorie",
            "Subcategory main": "Sous-catégorie principale",
            "Subcategory detail": "Sous-catégorie détaillée",
            "Subcategory": "Sous-catégorie",
            "Subcategory (free text)": "Sous-catégorie (texte libre)",
            "Supplier": "Fournisseur",
            "Supplier (free text)": "Fournisseur (texte libre)",
            "Product name": "Nom du produit",
            "Quantity": "Quantité",
            "Price": "Prix",
            "Date": "Date",
            "Save": "Enregistrer",
            "Please enter a product name.": "Veuillez entrer un nom de produit.",
            "Price must be greater than 0.": "Le prix doit être supérieur à 0.",
            "Added": "Ajouté",
            "Purchase History": "Historique des Achats",
            "No purchases found.": "Aucun achat trouvé.",
            "Deleted": "Supprimé",
            "on": "le",
            "Modify Entry": "Modifier l'entrée",
            "Product": "Produit",
            "Save Changes": "Enregistrer les modifications",
            "Cancel": "Annuler",
            "Entry updated successfully!": "Entrée mise à jour avec succès!",
            "Total": "Total",
            "Weekly Comparison": "Comparaison Hebdomadaire",
            "Statistics": "Statistiques",
            "Monthly Expenses": "Dépenses Mensuelles"
        },
        "ar": {
            "Add a product": "إضافة منتج",
            "Category": "الفئة",
            "Subcategory main": "الفئة الفرعية الرئيسية",
            "Subcategory detail": "الفئة الفرعية التفصيلية",
            "Subcategory": "الفئة الفرعية",
            "Subcategory (free text)": "الفئة الفرعية (نص حر)",
            "Supplier": "المورد",
            "Supplier (free text)": "المورد (نص حر)",
            "Product name": "اسم المنتج",
            "Quantity": "الكمية",
            "Price": "السعر",
            "Date": "التاريخ",
            "Save": "حفظ",
            "Please enter a product name.": "يرجى إدخال اسم المنتج.",
            "Price must be greater than 0.": "يجب أن يكون السعر أكبر من 0.",
            "Added": "تمت الإضافة",
            "Purchase History": "سجل المشتريات",
            "No purchases found.": "لا توجد مشتريات.",
            "Deleted": "تم الحذف",
            "on": "في",
            "Modify Entry": "تعديل الإدخال",
            "Product": "المنتج",
            "Save Changes": "حفظ التعديلات",
            "Cancel": "إلغاء",
            "Entry updated successfully!": "تم تحديث الإدخال بنجاح!",
            "Total": "الإجمالي",
            "Weekly Comparison": "المقارنة الأسبوعية",
            "Statistics": "الإحصائيات",
            "Monthly Expenses": "المصروفات الشهرية"
        }
    }
    # Retourne la traduction selon la langue, sinon la clé originale
    return translations.get(lang, translations["fr"]).get(key, key)

