# lang_utils.py

def get_translation(key: str, lang: str) -> str:
    translations = {
        "fr": {
            "Add a product": "Ajouter un produit",
            "Category": "Catégorie",
            "Subcategory main": "Sous-catégorie principale",
            "Subcategory detail": "Sous-catégorie détaillée",
            "Subcategory": "Sous-catégorie",
            "Subcategory (free text)": "Sous-catégorie (texte libre)",
            "Supplier": "Fournisseur",
            "Supplier (free text)": "Fournisseur (texte libre)",
            "Product name": "Nom du produit",
            "Quantity": "Quantité",
            "Price": "Prix",
            "Date": "Date",
            "Save": "Enregistrer",
            "Please enter a product name.": "Veuillez entrer un nom de produit.",
            "Price must be greater than 0.": "Le prix doit être supérieur à 0.",
            "Added": "Ajouté",
            "Purchase History": "Historique des Achats",
            "No purchases found.": "Aucun achat trouvé.",
            "Deleted": "Supprimé",
            "on": "le",
            "Modify Entry": "Modifier l'entrée",
            "Product": "Produit",
            "Save Changes": "Enregistrer les modifications",
            "Cancel": "Annuler",
            "Entry updated successfully!": "Entrée mise à jour avec succès!",
            "Total": "Total",
            "Weekly Comparison": "Comparaison Hebdomadaire",
            "Statistics": "Statistiques",
            "Monthly Expenses": "Dépenses Mensuelles",
            "Catégorie": "Catégorie",
            "Sous-catégorie principale": "Sous-catégorie principale",
            "Sous-catégorie détaillée": "Sous-catégorie détaillée",
            "Sous-catégorie": "Sous-catégorie",
            "Sous-catégorie (libre)": "Sous-catégorie (libre)",
            "Fournisseur": "Fournisseur",
            "Fournisseur (libre)": "Fournisseur (libre)",
            "Nom du produit": "Nom du produit",
            "Quantité": "Quantité",
            "Prix d'achat unitaire (TND)": "Prix d'achat unitaire (TND)",
            "Prix de vente unitaire (TND)": "Prix de vente unitaire (TND)",
            "Date": "Date",
            "Enregistrer": "Enregistrer",
            "⚠️ Veuillez saisir un nom de produit.": "⚠️ Veuillez saisir un nom de produit.",
            "⚠️ Le prix de vente doit être supérieur ou égal au prix d'achat.": "⚠️ Le prix de vente doit être supérieur ou égal au prix d'achat.",
            "Aucun achat/vente enregistré.": "Aucun achat/vente enregistré.",
            "Historique Achat/Vente": "Historique Achat/Vente",
            "Télécharger l'historique en Excel": "Télécharger l'historique en Excel",
            "Télécharger l'historique en PDF": "Télécharger l'historique en PDF",
            "🔄 Rafraîchir la page": "🔄 Rafraîchir la page",
            "Ajouter un achat/vente": "Ajouter un achat/vente"
        },
        "ar": {
            "Add a product": "إضافة منتج",
            "Category": "الفئة",
            "Subcategory main": "الفئة الفرعية الرئيسية",
            "Subcategory detail": "الفئة الفرعية التفصيلية",
            "Subcategory": "الفئة الفرعية",
            "Subcategory (free text)": "الفئة الفرعية (نص حر)",
            "Supplier": "المورد",
            "Supplier (free text)": "المورد (نص حر)",
            "Product name": "اسم المنتج",
            "Quantity": "الكمية",
            "Price": "السعر",
            "Date": "التاريخ",
            "Save": "حفظ",
            "Please enter a product name.": "يرجى إدخال اسم المنتج.",
            "Price must be greater than 0.": "يجب أن يكون السعر أكبر من 0.",
            "Added": "تمت الإضافة",
            "Purchase History": "سجل المشتريات",
            "No purchases found.": "لا توجد مشتريات.",
            "Deleted": "تم الحذف",
            "on": "في",
            "Modify Entry": "تعديل الإدخال",
            "Product": "المنتج",
            "Save Changes": "حفظ التعديلات",
            "Cancel": "إلغاء",
            "Entry updated successfully!": "تم تحديث الإدخال بنجاح!",
            "Total": "الإجمالي",
            "Weekly Comparison": "المقارنة الأسبوعية",
            "Statistics": "الإحصائيات",
            "Monthly Expenses": "المصروفات الشهرية",
            "Catégorie": "الفئة",
            "Sous-catégorie principale": "الفئة الفرعية الرئيسية",
            "Sous-catégorie détaillée": "الفئة الفرعية التفصيلية",
            "Sous-catégorie": "الفئة الفرعية",
            "Sous-catégorie (libre)": "الفئة الفرعية (نص حر)",
            "Fournisseur": "المورد",
            "Fournisseur (libre)": "المورد (نص حر)",
            "Nom du produit": "اسم المنتج",
            "Quantité": "الكمية",
            "Prix d'achat unitaire (TND)": "سعر الشراء للوحدة (TND)",
            "Prix de vente unitaire (TND)": "سعر البيع للوحدة (TND)",
            "Date": "التاريخ",
            "Enregistrer": "حفظ",
            "⚠️ Veuillez saisir un nom de produit.": "⚠️ يرجى إدخال اسم المنتج.",
            "⚠️ Le prix de vente doit être supérieur ou égal au prix d'achat.": "⚠️ يجب أن يكون سعر البيع أكبر أو يساوي سعر الشراء.",
            "Aucun achat/vente enregistré.": "لا يوجد سجل للشراء/البيع.",
            "Historique Achat/Vente": "سجل الشراء/البيع",
            "Télécharger l'historique en Excel": "تحميل السجل بصيغة Excel",
            "Télécharger l'historique en PDF": "تحميل السجل بصيغة PDF",
            "🔄 Rafraîchir la page": "🔄 إعادة تحميل الصفحة",
            "Ajouter un achat/vente": "إضافة شراء/بيع"
        }
    }
    # Retourne la traduction selon la langue, sinon la clé originale
    return translations.get(lang, translations["fr"]).get(key, key)

